In [1]:
### Following the intros to PyTorch

### Tensors and Variables 

import torch
x1d = torch.Tensor([1,2,3])
print(x1d)
x2d = torch.Tensor([[1,2,3],[3,4,5]])
print(x2d)

tensor([1., 2., 3.])
tensor([[1., 2., 3.],
        [3., 4., 5.]])


In [2]:
### Initialize Random
x =  torch.Tensor(2, 3) 
print(x)
y = torch.rand(2, 3)    # Initialize with random values
print(y)

tensor([[                              0.0000,
                                       0.0000,
                                      70.7660],
        [-158494935096892617406355079168.0000,
                                       0.0000,
                                       0.0000]])
tensor([[0.3123, 0.0013, 0.5513],
        [0.3299, 0.1243, 0.1945]])


In [3]:
### Operations
z1 = x + y
print(z1)  

z2 = torch.add(x, y)             # Same as above
print(z2)

tensor([[                              0.3123,
                                       0.0013,
                                      71.3173],
        [-158494935096892617406355079168.0000,
                                       0.1243,
                                       0.1945]])
tensor([[                              0.3123,
                                       0.0013,
                                      71.3173],
        [-158494935096892617406355079168.0000,
                                       0.1243,
                                       0.1945]])


In [4]:
### Basic Tensor operation
x = torch.Tensor(6, 2)
print(x)
print(x.size())                        # torch.Size([6, 2])
torch.numel(x)                  # 6: number of elements in x

tensor([[0.0000, 0.0000],
        [0.0000, 0.0000],
        [0.0000, 0.0000],
        [0.0000, 0.0000],
        [0.0000, 0.0000],
        [0.0000, 0.0000]])
torch.Size([6, 2])


12

In [5]:
### Tensor resizing / reshaping.
x = torch.randn(2, 3)            # Size 2x3
print(x)
y = x.view(6)                    # Resize x to size 6. 
print(y)
z = x.view(-1, 3)                # Size same
print(z)
z = x.view(-1, 2)                # Size 3x2
print(z)
z = x.view(-1, 1)                # Size 6
print(z)

tensor([[-0.8248, -1.3497, -0.3734],
        [ 0.0420,  0.2231,  1.2795]])
tensor([-0.8248, -1.3497, -0.3734,  0.0420,  0.2231,  1.2795])
tensor([[-0.8248, -1.3497, -0.3734],
        [ 0.0420,  0.2231,  1.2795]])
tensor([[-0.8248, -1.3497],
        [-0.3734,  0.0420],
        [ 0.2231,  1.2795]])
tensor([[-0.8248],
        [-1.3497],
        [-0.3734],
        [ 0.0420],
        [ 0.2231],
        [ 1.2795]])


In [6]:
#For reproducibility. Random initilizations.
torch.manual_seed(1)
v = torch.rand(2, 3)            # Initialize with random number (uniform distribution)
print(v)
v = torch.randn(2, 3)           # With normal distribution (SD=1, mean=0)
print(v)
v = torch.randperm(4)   # Random permutation
print(v)

tensor([[0.7576, 0.2793, 0.4031],
        [0.7347, 0.0293, 0.7999]])
tensor([[ 0.5636,  1.1431,  0.8590],
        [ 0.7056, -0.3406, -1.2720]])
tensor([2, 0, 1, 3])


In [7]:
### Indexing
# Can use numpy type indexing
# For assignment

x[:, 0] = 0                      
x = torch.rand(2,3)
print(x)
x[:,0]=1
print(x)
x[1,:]=5
print(x)

tensor([[0.1980, 0.4162, 0.2843],
        [0.3398, 0.5239, 0.7981]])
tensor([[1.0000, 0.4162, 0.2843],
        [1.0000, 0.5239, 0.7981]])
tensor([[1.0000, 0.4162, 0.2843],
        [5.0000, 5.0000, 5.0000]])


In [8]:
#Matrix : Identity and others.
eye = torch.eye(3)              # Create an identity 3x3 tensor
print(eye)

v = torch.ones(10)              # A tensor of size 10 containing all ones
print(v)
v = torch.ones(2, 1, 2, 1)      # Size 2x1x2x1
print(v)
v = torch.ones_like(eye)        # A tensor with same shape as eye. Fill it with 1.
print(v)
v = torch.zeros(10)             # A tensor of size 10 containing all zeros
print(v)

# 1  1  1
# 2  2  2
# 3  3  3
v = torch.ones(3, 3)
print(v)
v[1].fill_(2)
print(v)
v[2].fill_(3)
print(v)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([[[[1.],
          [1.]]],


        [[[1.],
          [1.]]]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [2., 2., 2.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.]])


In [9]:
# Initialize Tensor with a range of value
v = torch.arange(5)             # similar to range(5) but creating a Tensor
print(v)
v = torch.arange(0, 5, step=1)  # Size 5. Similar to range(0, 5, 1)
print(v)
v = torch.arange(0, 5, step=2)  # Size 5. Similar to range(0, 5, 2)
print(v)
# 0 1 2
# 3 4 5
# 6 7 8
v = torch.arange(9)
print(v)
v = v.view(3, 3)
print(v)

tensor([0, 1, 2, 3, 4])
tensor([0, 1, 2, 3, 4])
tensor([0, 2, 4])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [10]:
# Initialize a linear or log scale Tensor
v = torch.linspace(1, 10, steps=10) # Create a Tensor with 10 linear points for (1, 10) inclusively
print(v)
v = torch.logspace(start=-10, end=10, steps=5) # Size 5: 1.0e-10 1.0e-05 1.0e+00, 1.0e+05, 1.0e+10
print(v)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])


In [11]:
### From numpy and to numpy.
import numpy as np

a = np.array([1,2])
print(a)
b = torch.from_numpy(a)
print(b)
b = b**2
c = b.numpy()
print(c)

[1 2]
tensor([1, 2])
[1 4]


In [12]:
### Variables and Gradients

from torch.autograd import Variable
a = Variable(torch.Tensor([1,2]), requires_grad=True)
print(a)

y = torch.sum(a**2) # 1 + 4 
print(y)

y.backward()       # compute gradients of y wrt a
print(a.grad)      # print dy/da_ij = 2*a_ij for a_11, a_12
#Variable containing:  2  4

tensor([1., 2.], requires_grad=True)
tensor(5., grad_fn=<SumBackward0>)
tensor([2., 4.])
